In [44]:
import pandas as pd

In [45]:
Q_FILE = '/mnt/d/幽门螺旋杆菌/Script/分析结果/ADMIXTURE/data/WGS.aln.fasta.CDS_地理东亚及周边_3378_filtered.6.Q'
FAM_FILE = '/mnt/d/幽门螺旋杆菌/Script/分析结果/ADMIXTURE/data/WGS.aln.fasta.CDS_地理东亚及周边_3378_filtered.fam'
META_FILE = '/mnt/f/OneDrive/文档（科研）/P0_幽门螺旋杆菌/基础信息表/HP数据收集2.xlsx'

In [46]:
df_Q = pd.read_csv(Q_FILE, sep=' ', header=None)
df_Q.columns = [f'K{i+1}' for i in range(df_Q.shape[1])]
df_fam = pd.read_csv(FAM_FILE, sep='\t', header=None).loc[:,[0,1]]
df_fam.columns = ['FID', 'ID']
df_fam

            FID               ID
0       hpAsia2  HEL_BA5585AA_AS
1       hpAsia2  HEL_BA8063AA_AS
2       hpAsia2  HEL_BA8388AA_AS
3       hpAsia2  HEL_CA4141AA_AS
4       hpAsia2  HEL_CA4533AA_AS
...         ...              ...
3373    hspUral  HEL_CA4170AA_AS
3374  hpSiberia  GCA_016749815.1
3375  hpSiberia  GCA_016755615.1
3376  hpSiberia  HEL_AA7241AA_AS
3377  hpSiberia  HEL_AA7365AA_AS

[3378 rows x 2 columns]

In [47]:
df_Q

            K1        K2        K3        K4        K5        K6
0     0.000010  0.000010  0.999950  0.000010  0.000010  0.000010
1     0.000010  0.000010  0.999950  0.000010  0.000010  0.000010
2     0.000013  0.000010  0.999947  0.000010  0.000010  0.000010
3     0.000010  0.000010  0.999950  0.000010  0.000010  0.000010
4     0.000012  0.000010  0.999948  0.000010  0.000010  0.000010
...        ...       ...       ...       ...       ...       ...
3373  0.000010  0.000010  0.304150  0.058550  0.637270  0.000010
3374  0.145588  0.158056  0.021750  0.139937  0.487674  0.046995
3375  0.103213  0.105936  0.061105  0.213558  0.475249  0.040940
3376  0.085565  0.041657  0.000010  0.007977  0.864780  0.000010
3377  0.145689  0.130404  0.000010  0.018913  0.704973  0.000010

[3378 rows x 6 columns]

In [48]:
# 将Q矩阵与fam文件合并
df_Q_fam = pd.concat([df_fam, df_Q], axis=1)
df_Q_fam

,FID,ID,K1,K2,K3,K4,K5,K6
0,hpAsia2,HEL_BA5585AA_AS,0.000010,0.000010,0.999950,0.000010,0.000010,0.000010
1,hpAsia2,HEL_BA8063AA_AS,0.000010,0.000010,0.999950,0.000010,0.000010,0.000010
2,hpAsia2,HEL_BA8388AA_AS,0.000013,0.000010,0.999947,0.000010,0.000010,0.000010
3,hpAsia2,HEL_CA4141AA_AS,0.000010,0.000010,0.999950,0.000010,0.000010,0.000010
4,hpAsia2,HEL_CA4533AA_AS,0.000012,0.000010,0.999948,0.000010,0.000010,0.000010
...,...,...,...,...,...,...,...,...
3373,hspUral,HEL_CA4170AA_AS,0.000010,0.000010,0.304150,0.058550,0.637270,0.000010
3374,hpSiberia,GCA_016749815.1,0.145588,0.158056,0.021750,0.139937,0.487674,0.046995
3375,hpSiberia,GCA_016755615.1,0.103213,0.105936,0.061105,0.213558,0.475249,0.040940
3376,hpSiberia,HEL_AA7241AA_AS,0.085565,0.041657,0.000010,0.007977,0.864780,0.000010
3377,hpSiberia,HEL_AA7365AA_AS,0.145689,0.130404,0.000010,0.018913,0.704973,0.000010

In [49]:
df_meta = pd.read_excel(META_FILE, sheet_name='HP数据收集').loc[:,['ID','Latitude','Longitude']]
df_meta.head()

                ID   Latitude  Longitude
0  HEL_CA3782AA_AS   5.000000 -72.000000
1  HEL_AA0356AA_AS  46.227640   2.213749
2  HEL_AA1847AA_AS  46.227640   2.213749
3  HEL_AA4346AA_AS  12.150556 -86.268056
4  HEL_AA5463AA_AS  13.000000 -15.000000

In [50]:
# 合并数据
df_combined = pd.merge(df_Q_fam, df_meta, left_on='ID', right_on='ID', how='left')
df_combined.head()

,FID,ID,K1,K2,K3,K4,K5,K6,Latitude,Longitude
0,hpAsia2,HEL_BA5585AA_AS,0.000010,0.00001,0.999950,0.00001,0.00001,0.00001,4.210484,101.97580
1,hpAsia2,HEL_BA8063AA_AS,0.000010,0.00001,0.999950,0.00001,0.00001,0.00001,4.210484,101.97580
2,hpAsia2,HEL_BA8388AA_AS,0.000013,0.00001,0.999947,0.00001,0.00001,0.00001,4.210484,101.97580
3,hpAsia2,HEL_CA4141AA_AS,0.000010,0.00001,0.999950,0.00001,0.00001,0.00001,23.684990,90.35633
4,hpAsia2,HEL_CA4533AA_AS,0.000012,0.00001,0.999948,0.00001,0.00001,0.00001,20.593684,78.96288

In [51]:
df_combined.to_csv('/mnt/c/Users/Administrator/Desktop/ADMIXTURE.csv', index=False)